### ISSUE TITLE
AG accessions are out of date

### ISSUE THREAD

**Issue by wasade** [PersonalGenomesOrg/open-humans-data-processing#10]
The sample to accession map is [here](https://github.com/biocore/American-Gut/blob/master/data/AG/sample_to_accession.json) and accession to sample map is [here](https://github.com/biocore/American-Gut/blob/master/data/AG/accession_to_sample.json).

**Comment by madprime** [comment]
@wasade: The barcodes I think Open Humans receives are typically just a 9 digit string, without the second part. This matches the library_name, e.g. here: http://www.ebi.ac.uk/ena/data/warehouse/filereport?accession=ERP003819&result=read_run&fields=sample_accession,library_name

AIUI in the results of the link above, the barcode `000007080` matches `000007080:4`.

But the json you made has a second part to the barcodes, and it doesn't seem to match this second part in the EBI library_name... what is it? is it useful/needed? I don't think it's passed to Open Humans? For example, for this barcode, the json reads: `000007080.1075651`.

Also, I built around a mapping of barcode to _sample_ accession, not study accession... e.g. `SAMEA2176215`. So from the barcode `000007080` I can jump directly to the sample data page and get links to the files I need.... for example: http://www.ebi.ac.uk/ena/data/warehouse/filereport?accession=SAMEA2176215&result=read_run

I also use the sample accession to get the metadata, for example: http://www.ebi.ac.uk/ena/data/view/SAMEA2176215&display=xml

So... I think what I need is the sample accessions, I've been looking them up from the study accessions to generate the barcode_to_sample_accession.json file. :)

For now I'm regenerating the file to add the barcode → sample accession info for the new study accessions.

**Comment by beaugunderson** [comment]
Just noting that the decision to only send the `000007080` from American Gut to Open Humans was one that I made based on what I thought we needed; I can augment that with additional identifiers if they're available and needed. :)

**Comment by wasade** [comment]
Just to follow up, the sample ID includes both the barcode and the suffix.
The reason the barcode itself is insufficient is in the case where a sample
has been sequenced twice, which does happen to a subset of samples
(although our own results viewers do not disambiguate as the results are
per-sample, not per-sample-per-sequencing, and something we need to
resolve). Does this make sense?
