### ISSUE TITLE
Make all filenames match format of PGP filenames [3]

### ISSUE THREAD

**Issue by beaugunderson** [PersonalGenomesOrg/open-humans-data-processing#7]

**Comment by beaugunderson** [comment]
OK, I updated the filenames to look like so:

```
23andme_individual-058e958a740ab412_full-genotype-data_20150304174829.tar.gz
american-gut_sample-000007080_microbiome-16s_20150304174829.tar.gz
go-viral_id-individual_sickness-reports_20150304174829.tar.gz
pgp-harvard_individual-hu43860C_genome_20150304174829.tar.gz
pgp-harvard_individual-hu43860C_surveys_20150304174829.tar.gz
```

The standard I followed was:
- all lowercase
- dashes only
- `study_identifier_data-type_date.tar.gz`

What do you think @madprime?

**Comment by beaugunderson** [comment]
One note is that 'simplelogin-5' could be simplified to '5' for GoViral.

**Comment by beaugunderson** [comment]
Probably best to leave feedback on the [pull request](https://github.com/PersonalGenomesOrg/open-humans-data-processing/pull/8). :)

**Comment by madprime** [comment]
let's change "microbiome-16s" instead of "full-microbiome"

**Comment by madprime** [comment]
also let's change GoViral's "reports" to "sickness-reports"

**Comment by beaugunderson** [comment]
ISO8601 dates would be great but they contain colons: 2015-03-04T12:43:20Z
